import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "School-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/logo.png" />
      </head>
      <body suppressHydrationWarning>
        <Navbar />
        <main className="pt-4">{children}</main>
      </body>
    </html>
  );
}
